### ISSUE TITLE
Scrollbug in fixed div

### ISSUE THREAD

**Issue by DevidraEX** [claviska/jquery-dropdown#94] opened 2015-08-11 20:11 UTC
Thanks for the nice script, work like a charm, just a little "bug" which is nearly the same as this one ( https://github.com/claviska/jquery-dropdown/issues/84 )

I got a "fixed" headernavigation, if I open the dropdown, it work, if I resize the window it work too

JUST, if I scroll down/up the dropdown stay where I open it instead scroll with the fixed header

![normal](https://cloud.githubusercontent.com/assets/8301472/9209269/dc466940-4075-11e5-93ec-bd024c18ed45.png)
![scrolled](https://cloud.githubusercontent.com/assets/8301472/9209270/df2698a6-4075-11e5-94c2-d85f405d462f.png)

**Comment by whelaro** [comment] 2015-12-31 23:14
this appears to be a duplicate of #84

**Comment by claviska** [comment] 2017-01-14 15:52
Closing as duplicate.

**Closed by claviska** 2017-01-14 15:52 UTC
Labels: Duplicate
